# Use an official Python runtime as a parent image
FROM python:3.8-alpine

# Set the working directory to /app
WORKDIR /app

# Clone the GitHub repository into the container
# RUN git clone https://github.com/joshwizard/Vividarts_Studio_Project

# Copy the contents of the local app directory to the container at /app
#COPY requirements.txt requirements.txt

RUN python -m pip install --upgrade pip
COPY . /app


# Install any dependencies needed for your application
RUN pip install -r requirements.txt

# Make port 5000 available to the world outside this container
EXPOSE 5000

# Define environment variable
#ENV NAME World

# Run app.py when the container launches
#CMD ["python", "app.py"]

CMD [ "python", "-m" , "flask", "run", "--host=0.0.0.0"]
